## Very first code

In [1]:
print("Hello world!")

Hello world!


In [2]:
import numpy as np

### create a single-dimension Array 1x3

In [3]:
a1x3 = np.array([1,2,3])
print(a1x3)

[1 2 3]


### create a multi-dimension Array 2x3

In [4]:
a2x3 = np.array([(1,2,3),(4,5,6)])
print(a2x3)

[[1 2 3]
 [4 5 6]]


In [5]:
a3x3 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a3x2 = np.array([(1,2),(3,4),(5,6)])
print(a3x2)

[[1 2]
 [3 4]
 [5 6]]


### Số chiều của mảng ndim

In [7]:
print(a1x3.ndim)
print(a2x3.ndim)
print(a3x3.ndim)
print(a3x2.ndim)

1
2
2
2


### Kích thước mảng size

In [8]:
print(a1x3.size)
print(a2x3.size)
print(a3x3.size)

3
6
9


### Thay đổi hình dạng array reshape

In [9]:
print(a2x3)
print(a2x3.reshape(3,2))
print(a2x3.reshape(1,6))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]


In [10]:
a3x4 = np.array([(3,4,5,6),(5,6,7,8),(3,4,7,8)])
print(a3x4)

[[3 4 5 6]
 [5 6 7 8]
 [3 4 7 8]]


### Min/Max của array

In [11]:
print(a3x4.min())
print(a3x4.max())
print(a2x3.min())
print(a2x3.max())

3
8
1
6


### Tổng các phần tử trong array

In [12]:
print(a2x3)
print(a2x3.sum())
print(a3x4)
print(a3x4.sum())

[[1 2 3]
 [4 5 6]]
21
[[3 4 5 6]
 [5 6 7 8]
 [3 4 7 8]]
66


### Tính tổng theo hàng và cột
#### Cột - axis = 0 / Hàng - axis = 1

In [13]:
print(a2x3)
print(a2x3.sum(axis=0))
print(a3x4)
print(a3x4.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[[3 4 5 6]
 [5 6 7 8]
 [3 4 7 8]]
[18 26 22]


### Căn bậc 2 của array - sqrt (square root)

In [14]:
print(a2x3)
print(np.sqrt(a2x3))

[[1 2 3]
 [4 5 6]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


### Độ lệch chuẩn std (standard deviation)

In [15]:
print(a2x3)
print(np.std(a2x3))

[[1 2 3]
 [4 5 6]]
1.707825127659933


In [16]:
a1 = np.array([(1,1,1),(2,2,2)])
a2 = np.array([(2,2,2),(3,3,3)])
a3 = np.array([(1,1),(2,2),(3,3)])
a4 = np.array([(1,1,1),(2,2,2),(3,3,3)])
print("--- Các phép toán ma trận ---")
print(a1)
print(a2)
print("--- Phép cộng ma trận ---")
print(a1 + a2)
print("--- Phép trừ ma trận ---")
print(a2 - a1)
print("--- Phép nhân ma trận ---")
print(a1)
print(a3)
print(a1 @ a3)

--- Các phép toán ma trận ---
[[1 1 1]
 [2 2 2]]
[[2 2 2]
 [3 3 3]]
--- Phép cộng ma trận ---
[[3 3 3]
 [5 5 5]]
--- Phép trừ ma trận ---
[[1 1 1]
 [1 1 1]]
--- Phép nhân ma trận ---
[[1 1 1]
 [2 2 2]]
[[1 1]
 [2 2]
 [3 3]]
[[ 6  6]
 [12 12]]


### Invert matrix - Ma trận nghịch đảo

In [17]:
print(a2x3)
a2x3_i = np.linalg.pinv(a2x3)
print("--- Ma trận nghịch đảo ---")
print(a2x3_i)
print("--- Kết quả nhân với ma trận nghịch đảo ---")
print(a2x3 @ a2x3_i)

[[1 2 3]
 [4 5 6]]
--- Ma trận nghịch đảo ---
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]
--- Kết quả nhân với ma trận nghịch đảo ---
[[ 1.00000000e+00  3.05311332e-16]
 [-4.44089210e-16  1.00000000e+00]]


### Transpose matrix - Chuyển vị ma trận

In [18]:
print(a2x3)
print("--- Chuyển vị ma trận ---")
print(np.transpose(a2x3))

[[1 2 3]
 [4 5 6]]
--- Chuyển vị ma trận ---
[[1 4]
 [2 5]
 [3 6]]


In [24]:
1.10 + 2.20

3.3000000000000003

In [35]:
from decimal import Decimal as D
D('1.10') + D('2.20')

Decimal('3.30')

#### Thêm .0 vào 4 vì phép toán với float thực hiện nhanh hơn Decimal

In [41]:
D('4.0')*D('2.5')

Decimal('10.00')

### Phân số

In [68]:
import fractions as F

In [47]:
print(fractions.Fraction('1.2'))

6/5


In [50]:
print(fractions.Fraction(1,2))

1/2


In [69]:
f1 = F.Fraction(2,5)
f2 = F.Fraction(3,5)

print(f1, f2, f1 + f2)

2/5 3/5 1


### List

In [71]:
list1 = [1,2,3,4,5]
print (list1)

[1, 2, 3, 4, 5]


In [73]:
list2 = [[1,2,3], 4, [5,6,7,8]]
print (list2)

[[1, 2, 3], 4, [5, 6, 7, 8]]


In [75]:
print (list2[1])

4


In [77]:
print(list2[0][1])

2


#### 0 [1] 1 [2] 2 [3] 3 [4] 4 [5]
##### trong dấu ngoặc là phần tử trong list
##### 0:2 sẽ lấy ra các phần tử từ vị trí 0 -> 2 => sẽ là 1, 2
##### 1:4 sẽ lấy ra các phần tử nằm giữa 1 và 4 => 2, 3, 4

In [80]:
print (list1[1:4])

[2, 3, 4]


In [82]:
print (list1[0:2])

[1, 2]


In [89]:
list2.append(8)
print(list2)

[[1, 2, 3], 4, [5, 6, 7, 8], 7, [7, 9], 7, 8, 8, 8]


In [95]:
list2[3] = 9
list2[4] = [10,11]
print(list2)

[[1, 2, 3], 4, [5, 6, 7, 8], 9, [10, 11], 7, 8, 8, 8]


In [100]:
del list2[5:]
print(list2)

[[1, 2, 3], 4, [5, 6, 7, 8], 9, [10, 11]]


In [106]:
list1.reverse()
print(list1)

[5, 4, 3, 2, 1]


In [111]:
print(min(list1), max(list1), len(list1), sum(list1))

1 5 5 15


### Dictionary

In [116]:
dic1 = {1: "Networking", 2: "Hacking", 3: "ASP.NET", 4:"Machine Learning", 5:"English"}
print(dic1)

{1: 'Networking', 2: 'Hacking', 3: 'ASP.NET', 4: 'Machine Learning', 5: 'English'}


In [117]:
print(dic1[3], dic1[4], dic1[5])

ASP.NET Machine Learning English
